"""add line_item and creative tables.

Revision ID: 01bbd1772553
Revises: 3155e70ced19
Create Date: 2022-09-09 20:44:45.030334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01bbd1772553'
down_revision = '3155e70ced19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('line_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('max_impressions', sa.Integer(), nullable=False),
    sa.Column('rpm', sa.Numeric(), nullable=False),
    sa.Column('campaign_start', sa.TIMESTAMP(), nullable=True),
    sa.Column('campaign_end', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ad_unit_line_item',
    sa.Column('line_item_id', sa.Integer(), nullable=False),
    sa.Column('ad_unit_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ad_unit_id'], ['ad_unit.id'], ),
    sa.ForeignKeyConstraint(['line_item_id'], ['line_item.id'], ),
    sa.PrimaryKeyConstraint('line_item_id', 'ad_unit_id')
    )
    op.create_table('creative',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('creative_type', sa.Enum('IMAGE', 'HTML5', 'NATIVE', name='creativetype'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('width', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('height', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('line_item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['line_item_id'], ['line_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('creative')
    op.drop_table('ad_unit_line_item')
    op.drop_table('line_item')
    # ### end Alembic commands ###
