"""Create the Ad Unit table.

Revision ID: 3155e70ced19
Revises: 
Create Date: 2022-09-09 16:25:18.822099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3155e70ced19'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ad_unit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('country', sa.String(length=80), nullable=False),
    sa.Column('device', sa.Enum('MOBILE', 'DESKTOP', name='device'), nullable=False),
    sa.Column('browser', sa.Enum('SAFARI', 'CHROME', 'FIREFOX', 'NETSCAPE', name='browser'), nullable=False),
    sa.Column('language', sa.Enum('ENGLISH', 'HEBREW', 'JAPANESE', name='language'), nullable=False),
    sa.Column('os', sa.Enum('IOS', 'ANDROID', 'WINDOWS', name='operatingsystem'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country', 'device', 'browser', 'language', 'os', name='_ad_unit_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ad_unit')
    # ### end Alembic commands ###
