"""rename line_item_id to line_item on creative model

Revision ID: e85d50318cd1
Revises: 01bbd1772553
Create Date: 2022-09-10 10:43:05.331264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e85d50318cd1'
down_revision = '01bbd1772553'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('creative', sa.Column('line_item', sa.Integer(), nullable=False))
    op.drop_constraint('creative_line_item_id_fkey', 'creative', type_='foreignkey')
    op.create_foreign_key(None, 'creative', 'line_item', ['line_item'], ['id'])
    op.drop_column('creative', 'line_item_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('creative', sa.Column('line_item_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint('creative_line_item_fkey', 'creative', type_='foreignkey')
    op.create_foreign_key('creative_line_item_id_fkey', 'creative', 'line_item', ['line_item_id'], ['id'])
    op.drop_column('creative', 'line_item')
    # ### end Alembic commands ###
